### ISSUE TITLE
Semver break in 0.4.2

### ISSUE THREAD

**Issue by jbg** [kolapapa/surge-ping#14]
0.4.2 changes the return type of `surge_ping::Client::new()` from a `Result<T, E>` to an `impl Future<Output = Result<T, E>>` (because it is changed to an `async fn`), which is a breaking change, so the version should have been bumped to 0.5 to prevent dependent crates from suddenly failing to build.

Also, the git tag / GitHub release is missing for 0.4.2.

**Comment by kolapapa** [comment]
I also hesitated on whether to modify this version, It's better to upgrade.

I will release version `0.5.0` and yarnk version `0.4.2`.
