### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mickaelmagniez** [kolapapa/surge-ping#15]
Hi

I'm trying to use this library in some long running multithreaded application, involving pinging hosts, and RAM is consistently increasing

This is one small snippet ro reproduce the issue 

```
    let ip = "127.0.0.1".parse().unwrap();
    loop {
        let mut pinger = surge_ping::pinger(ip).await.unwrap();
        match pinger.ping(1).await {
            Ok((IcmpPacket::V4(packet), dur)) => println!("ok"),
            Ok((IcmpPacket::V6(packet), dur)) => println!("ok"),
            Err(e) => println!("{:?}", e)
        };
    }
```

I have the same issue using the client

```
    let ip = "127.0.0.1".parse().unwrap();
    let client = Client::new(&Config::default()).await.unwrap();
    loop {
        let mut pinger = client.pinger(ip).await;
        match pinger.ping(1).await {
            Ok((IcmpPacket::V4(packet), dur)) => println!("ok"),
            Ok((IcmpPacket::V6(packet), dur)) => println!("ok"),
            Err(e) => println!("{:?}", e)
        };
    }
```
Best regards

**Comment by kolapapa** [comment]
@mickaelmagniez  Thank's for your help in pointing out the problem.

I submitted a new branch([fix_memory_leak](https://github.com/kolapapa/surge-ping/tree/fix_memory_leak)) to try to solve this memory leak problem.

You can make the following changes in your `Cargo.toml` to test whether the new branch solves the problem:
```toml
[patch.crates.io]
surge_ping = { git = "https://github.com/kolapapa/surge-ping", branch = "fix_memory_leak"}

[dependencies]
surge_ping = "0.5.0"
```


`surge_ping::pinger` now is deprecated. 
```rust
#[deprecated(note="please use `ping` instead")]
async fn pinger(host: IpAddr) -> Result<Pinger, SurgeError> {}
```


In your test example, it should be changed to(**This will frequently create and destroy system socket, please try to create a `Client` and then construct a `Pinger`**):
```rust
let ip = "127.0.0.1".parse().unwrap();
loop {
    match surge_ping::ping(ip).await {
        Ok(_packet, duration) => println!("duration: {:.2?}", duration),
        Err(e) => println!("{:?}", e),
    };
}
```

**Comment by mickaelmagniez** [comment]
Is seems to work very well, many thanks for this quick fix.

Indeed, i'm already using the client, i post the "pinger" code just to provide a simple example.

**Comment by kolapapa** [comment]
> Is seems to work very well, many thanks for this quick fix.
> 
> Indeed, i'm already using the client, i post the "pinger" code just to provide a simple example.

You can use the new version (`0.5.1`) to build your program.
