### ISSUE TITLE
Info: Reason for upgrading to UdpSocket

### ISSUE THREAD

**Issue by fabracht** [kolapapa/surge-ping#23]
I was going through the code and I fount that you upgrade the raw socket to a std UdpSocket. I would like to know the reason for that?
Thank you,

**Comment by kolapapa** [comment]
Hi~ @fabracht . This is just to facilitate the conversion of `RawSocket`s async version. Previous versions used `tokio`'s `AsyncFd` and later used `tokio::net::UdpSocket` to support the `windows` platform(https://github.com/kolapapa/surge-ping/pull/11).
If you want a more detailed answer, I think we can ask @wladwm  to answer~

**Comment by wladwm** [comment]
Hi. Primary it's for interoperability (AsyncFd is available only on Unix). Secondary for idiomatic reasons - raw sockets are datagram sockets, so we can use async UdpSocket to handle it.
