### ISSUE TITLE
Potential Index Out of Bounds?

### ISSUE THREAD

**Issue by andrew-hoff** [kolapapa/surge-ping#24]
Is there anything preventing a malformed packet from causing an index out of bounds crash [here](https://github.com/kolapapa/surge-ping/blob/main/src/icmp/icmpv4.rs#L184)?

**Comment by kolapapa** [comment]
Fix: https://github.com/kolapapa/surge-ping/pull/26

**Comment by andrew-hoff** [comment]
Thank you!
