### ISSUE TITLE
Error generating Client using example code

### ISSUE THREAD

**Issue by wrac4242** [kolapapa/surge-ping#27]
When running the examples, it errors with the error `Operation not permitted (os error 1)`
this error happens on the creation of the client

**Comment by wrac4242** [comment]
if you need any more info, do lmk

**Comment by wrac4242** [comment]
command specifically was `cargo run --example "multi_ping"`
and output was
```    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/multi_ping`
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }```

**Comment by wrac4242** [comment]
host is on linux

**Comment by wrac4242** [comment]
I was able to get this working by using sudo, but that originally was not clear to me, should the docs be updated to reflect this?

**Comment by kolapapa** [comment]
> I was able to get this working by using sudo, but that originally was not clear to me, should the docs be updated to reflect this?

Thanks for your suggestion, I will update the `README.md` soon.

**Comment by kolapapa** [comment]
Description has been added https://github.com/kolapapa/surge-ping/commit/ae87ba51b2cd437ec4f60a530e7f02d1812c38c6
