### ISSUE TITLE
Unresolved imports when compiling surge-ping v0.7.3

### ISSUE THREAD

**Issue by ghost** [kolapapa/surge-ping#28]
Intellij Idea gives a build error when compiling client.rs I get the error. "Unresolved imports 'tokio::net::UdpSocket', 'tokio::task::JoinHandle'"
Not sure what to do as client.rs is part of the surge-ping crate. The code im trying to run is the example at the top of the README.md.

Thanks in advance.

**Comment by kolapapa** [comment]
@tahearmon Can you show me your test code and `Cargo.toml` file?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/117466528/201043850-8171216d-921f-4690-bd9b-c34c71dd4e91.png)

![image](https://user-images.githubusercontent.com/117466528/201043992-cd7eb74c-2eeb-40f4-8ff1-51a3798f7a42.png)

**Comment by kolapapa** [comment]
Modify this `Cargo.toml`

```toml
# tokio = "1.21.2"
tokio = { version = "1.21", features = ["full"]}
```
