### ISSUE TITLE
`Ping` permission denied, Is there a gentle way to debug with linux normal user?

### ISSUE THREAD

**Issue by mokeyish** [kolapapa/surge-ping#29]
Hello,  [surge-ping](https://github.com/kolapapa/surge-ping) is a nice library. 
But I encountered an error `Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }`, and I don't wan't swich to root user. 
Do you have better solution?

**Comment by kolapapa** [comment]
@mokeyish  try to use `surge-ping = 0.7.4`

**Comment by mokeyish** [comment]
Thanks!
The link bellow is the solution I found , but it's still inconvenient. The `cargo` rebuild the binary file, and `cargo` cannot set post-build script to setcap to the binary file again. It would be better if [surge-ping](https://github.com/kolapapa/surge-ping) be able to try to avoid `permission denied` probelm.

https://github.com/rust-pcap/pcap/issues/278#issuecomment-1309809549

**Comment by kolapapa** [comment]
@mokeyish HI! This issue is duplicated with [#30](https://github.com/kolapapa/surge-ping/issues/30). I plan to close it first. If you have any questions, please leave a message and I will consider reopening it~ Thanks for your feedback
