### ISSUE TITLE
Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

### ISSUE THREAD

**Issue by rikonaka** [kolapapa/surge-ping#35]
I have read the issues [here](https://github.com/kolapapa/surge-ping/issues/29), change the `surge-ping = "0.7.3"` to `surge-ping = "0.7.4"`, but I got another error.

```
error: failed to select a version for the requirement `surge-ping = "^0.7.4"`
candidate versions found which didn't match: 0.7.3, 0.7.2, 0.7.1, ...
```

**Comment by kolapapa** [comment]
Can you tell me more about your os? In addition, due to some problems, version `0.7.4` has been deprecated, and now version `0.8.0` has been released, you can try it.

**Comment by rikonaka** [comment]
> Can you tell me more about your os? In addition, due to some problems, version `0.7.4` has been deprecated, and now version `0.8.0` has been released, you can try it.

Hi, I still get error message `IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })` when I using the `0.8.0`, my OS is popos 22.04 with kernel 6.2.6 .

**Comment by kolapapa** [comment]
you can use the setcap command to give your program the `CAP_NET_RAW` capability
```shell
sudo setcap cap_net_raw+ep /path/to/your_bin
```
