### ISSUE TITLE
Not compiling?

### ISSUE THREAD

**Issue by alexkingnz** [kolapapa/surge-ping#9]
I'm a beginner at rust, just compiling your example from the front page.

rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

Can you tell me why I get unresolved symbols?  Thanks

`$ cargo run
   Compiling surge-ping v0.2.2
error[E0432]: unresolved import `tokio::io::unix`
 --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/surge-ping-0.2.2/src/unix.rs:6:16
  |
6 | use tokio::io::unix::AsyncFd;
  |                ^^^^ could not find `unix` in `io`

error[E0425]: cannot find function `spawn` in module `task`
   --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/surge-ping-0.2.2/src/ping.rs:145:15
    |
145 |         task::spawn(async move {
    |               ^^^^^ not found in `task`
    |
help: consider importing this function
    |
1   | use std::thread::spawn;
    |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `surge-ping`

To learn more, run the command again with --verbose.

`

**Comment by kolapapa** [comment]
What is your operating system? windows？

**Comment by alexkingnz** [comment]
Debian Linux
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by donpdonp** [comment]
surge-ping is missing the net and rt modules in tokio. you can add them yourself in your project's Cargo.toml
```
[dependencies]
tokio = { version = "1.7", features = ["time", "macros", "net", "rt"] }
surge-ping = "0.3.1"
```

**Comment by kolapapa** [comment]
> Debian Linux $ cat /etc/os-release PRETTY_NAME="Debian GNU/Linux 10 (buster)" NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

Has the problem been solved?
